### ISSUE TITLE
Could you please release to pypi?

### ISSUE THREAD

**Issue by wkentaro** [dimatura/pypcd#1]
I'd like to use this in ROS package.
Could you please release this to pypi?

**Comment by dimatura** [comment]
Oh you use ROS? I have some support for ROS coming up :) Let me clean it up a bit.

**Comment by wkentaro** [comment]
Yes, I use ROS to actuate Dual-armed robot in lab.

**Comment by dimatura** [comment]
Done! Only took me like forever.
