### ISSUE TITLE
is there any manual or tutorial code for pypcd

### ISSUE THREAD

**Issue by adioshun** [dimatura/pypcd#13]
hi. thanks for your works. 

is there any manual or tutorial code for pypcd

**Comment by DanielPollithy** [comment]
Hi @adioshun !

I wrote a step by step introduction (blog post) about pypcd.
It covers: 

- Loading a .pcd file
- Some explanations about the file format
- numpy manipulation of the point cloud
- 2d and 3d visualization
- generation of a synthetic point cloud
- saving the cloud to disk

[http://blog.pollithy.com/python/numpy/pointcloud/tutorial-pypcd](http://blog.pollithy.com/python/numpy/pointcloud/tutorial-pypcd)

I hope that helps!
Daniel

**Comment by adioshun** [comment]
Thanks . It is very helpfull
