### ISSUE TITLE
Unable to install via pip or whl

### ISSUE THREAD

**Issue by ajith3530** [dimatura/pypcd#34]
Error message:
Collecting pypcd
  Using cached https://files.pythonhosted.org/packages/44/2c/81a97605f112c3ecd01ae5d378f5c35f4eef843c71a031627788c650bc00/pypcd-0.1.1-py2.py3-none-any.whl
Collecting python-lzf (from pypcd)
  Using cached https://files.pythonhosted.org/packages/e3/33/b8f67bbe695ccc39f868ae55378993a7bde1357a0567803a80467c8ce1a4/python-lzf-0.2.4.tar.gz
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\envtoolchain\lib\site-packages (from pypcd) (1.18.4)
Building wheels for collected packages: python-lzf
  Building wheel for python-lzf (setup.py) ... error
  ERROR: Complete output from command 'C:\ProgramData\Anaconda3\envs\envToolchain\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Z0007157\\AppData\\Local\\Temp\\pip-install-lqerxxna\\python-lzf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"'
, open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Z0007157\AppData\Local\Temp\pip-wheel-7g46w_95' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'lzf' extension
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -I. -IC:\ProgramData\Anaconda3\envs\envToolchain\include -IC:\ProgramData\Anaconda3\envs\envToolchain\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tclzf_module.c /Fobuild\temp.win-amd64-3.7\Rel
ease\lzf_module.obj -Wall
  error: command 'cl.exe' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for python-lzf
  Running setup.py clean for python-lzf
Failed to build python-lzf
Installing collected packages: python-lzf, pypcd
  Running setup.py install for python-lzf ... error
    ERROR: Complete output from command 'C:\ProgramData\Anaconda3\envs\envToolchain\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Z0007157\\AppData\\Local\\Temp\\pip-install-lqerxxna\\python-lzf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'
"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Z0007157\AppData\Local\Temp\pip-record-ocav5mr9\install-record.txt' --single-version-externally-managed --compil
e:
    ERROR: running install
    running build
    running build_ext
    building 'lzf' extension
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -I. -IC:\ProgramData\Anaconda3\envs\envToolchain\include -IC:\ProgramData\Anaconda3\envs\envToolchain\include "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tclzf_module.c /Fobuild\temp.win-amd64-3.7\R
elease\lzf_module.obj -Wall
    error: command 'cl.exe' failed: No such file or directory
    ----------------------------------------
ERROR: Command "'C:\ProgramData\Anaconda3\envs\envToolchain\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Z0007157\\AppData\\Local\\Temp\\pip-install-lqerxxna\\python-lzf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code
=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Z0007157\AppData\Local\Temp\pip-record-ocav5mr9\install-record.txt' --single-version-externally-managed --compile" failed with error cod
e 1 in C:\Users\Z0007157\AppData\Local\Temp\pip-install-lqerxxna\python-lzf\

**Comment by sebaleme** [comment]
Hi, I have the same issue. It seems you can t install pypcd with **pip install pypcd** in a windows environment. I Tried in Ubuntu, it works straight away. Note that Python 3 is required.

**Comment by ajith3530** [comment]
Hi, I just tried to install it again now, after seeing your comment, and the installation was successful. Maybe they fixed it now. I am using Python 3.6.5

**Comment by esuhonen** [comment]
@ajith3530 did you do it still on a Windows environment? Just with basic pip install pypcd command, or something else? Which Microsoft Visual C++ version you have? Im using Jupyter Notebook on Windows 10. Please give me details :)

**Comment by esuhonen** [comment]
> @ajith3530 did you do it still on a Windows environment? Just with basic pip install pypcd command, or something else? Which Microsoft Visual C++ version you have? Im using Jupyter Notebook on Windows 10. Please give me details :)

I'm trying to pip install through terminal...

**Comment by ajith3530** [comment]
I am using Windows 10. I have Microsoft Visual C++ 2019 version. I am using Pycharm IDE, so I used the conda environment terminal (which is basically cmd) to run the pipi install pypcd command.
